[project]
name = "echomess"
version = "0.1.0"
description = "Simple Python messenger using Sebsocket's"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "loguru>=0.7.3",
    "pwdlib[argon,argon2,argonv2]>=0.3.0",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "redis>=8.1.0",
    "sqlalchemy>=2.0.51",
    "uvicorn[standard]>=0.52.1",
    "uvloop>=0.22.1",
]
