[project]
name = "echomess"
version = "0.1.0"
description = "Simple Python messenger using Sebsocket's"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "loguru>=0.7.3",
    "pydantic-settings>=2.14.2",
    "redis>=8.1.0",
    "uvicorn[standard]>=0.52.1",
    "uvloop>=0.22.1",
]
