[project]
name = "echomess"
version = "0.1.0"
description = "Simple Python messenger using Sebsocket's"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "itsdangerous>=2.2.0",
    "loguru>=0.7.3",
    "pwdlib[argon,argon2,argonv2]>=0.3.0",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "redis>=8.1.0",
    "resend>=2.35.0",
    "ruff>=0.16.1",
    "sqlalchemy>=2.0.51",
    "uvicorn[standard]>=0.52.1",
    "uvloop>=0.22.1",
]

[tool.ruff.lint]
# only runtime-errors
select = [
    "E9",   # (SyntaxError, IndentationError)
    "PLE",  # Pylint Errors
    "F821",
]

ignore = [
    "F401", # (imported but unused)
    "F841", # (assigned but never used)
]
