upstream backend {
    server chat:8000;
}

server {
    listen 443 ssl;
    server_name echomess.fun;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://backend/;
    }

    ssl_certificate /etc/letsencrypt/live/echomess.fun/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/echomess.fun/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    location /wc/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Authorization "Bearer $arg_token";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://backend;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
