name: ECHOMESS CI/CD Pipeline

on:
  push:

jobs:
  #                           ---~~~--- CI ---~~~---
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Run Tests in Docker
        run: |
          cd backend && uv run ruff check . --isolated --select E9,PLE,F821 --ignore F401,F841

  #                           ---~~~--- CD ---~~~---
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'develop')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            bash -c '
              set -e
              cd ~/projects/echomess/
              BRANCH="${{ github.ref_name }}"
              docker compose down
              git fetch --all
              git switch "$BRANCH"
              git pull origin "$BRANCH"
              COMMIT_SHA="${{ github.sha }}" docker compose up --build -d
            '
